steps:
  - name: "gcr.io/$PROJECT_ID/helm"
    entrypoint: "bash"
    args: ["helm_deploy.sh"]
    env:
      - "ENV=$_ENV"
      - "CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER"
      - "PROJECT_ID=$PROJECT_ID"