apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cicd-testing-vue"
  namespace: "default"
  labels:
    app: "cicd-testing-vue"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "cicd-testing-vue"
  template:
    metadata:
      labels:
        app: "cicd-testing-vue"
    spec:
      containers:
      - name: "cicd-testing-vue"
        image: "asia.gcr.io/ssc-windows-ui-staging/cicd-testing-vue@sha256:560db74485d482af0969df80e52aeaac9d725f97d4cf4714a0a9ebdd787f6555"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
