apiVersion: v1
kind: Service
metadata:
  name: "cicd-testing-vue"
  labels:
    app: "cicd-testing-vue"
    service: "cicd-testing-vue"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: "cicd-testing-vue"
